# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
defaults:
  run:
    shell: bash
    working-directory: /home/ec2-user
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    steps:
      - name: firstTest
        run: |
          echo "A initial message"
          pwd
          echo "Another message or command"
    # The type of runner that the job will run on
    runs-on: self-hosted
